# Uncomment the next line to define a global platform for your project
   platform :ios, '8.0'

target 'StoneRoom' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for StoneRoom

  target 'StoneRoomTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'AFNetworking'
    pod 'Reveal-SDK','~> 4' ,:configurations => ['Debug'] #Reveal 2
    #七牛
    pod 'Qiniu', '~> 7.1'
    #数据库
    pod 'FMDB', '~> 2.6.2'
    pod 'MJExtension', '~> 3.0.13'
    pod 'MBProgressHUD'
    pod 'SDWebImage'

  end

  target 'StoneRoomUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
