# Uncomment the next line to define a global platform for your project
   platform :ios, '8.0'

target 'StoneRoom' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for StoneRoom

  target 'StoneRoomTests' do
    inherit! :search_paths
    # Pods for testing
    pod "AFNetworking"
    pod 'Reveal-SDk','~> 4',:configurations => ['Debug']

  end

  target 'StoneRoomUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
